app/admin/views/comment.py
from .. import admin
from flask import render_template, redirect, url_for
from ...models import Comment, User, Movie
from ...models import db
from .decorator import admin_login_decorator

# 评论列表
@admin.route("/comment/list/<int:page>/", methods=["GET"])
@admin_login_decorator
def comment_list(page=None):
    page_data = Comment.query.join(
        User
    ).join(
        Movie
    ).filter(
        User.id == Comment.user_id,
        Movie.id == Comment.movie_id
    ).order_by(
        Comment.add_time.desc()
    ).paginate(page=page, per_page=20)

    return render_template('admin/comment_list.html', page_data=page_data)


# 删除评论
@admin.route("/comment/del/<int:id>/", methods=["GET"])
@admin_login_decorator
def comment_del(id=None):
    comment = Comment.query.filter_by(id=id).first_or_404()  # <Comment 45>
    """
    comment = Comment.query.filter_by(id=id)
    SELECT comment.id AS comment_id, comment.content AS comment_content, comment.add_time AS comment_add_time, comment.movie_id AS comment_movie_id, comment.user_id AS comment_user_id 
    FROM comment 
    WHERE comment.id = %(id_1)s
    """
    db.session.delete(comment)
    db.session.commit()
    db.session.remove()
    return redirect(url_for('admin.comment_list', page=1))

app/admin/views/moviecol.py
from .. import admin
from .decorator import admin_login_decorator
from ... import models
from flask import render_template, redirect, url_for
from ...models import db


# 收藏列表
@admin.route("/moviecol/list/<int:page>")
@admin_login_decorator
def moviecol_list(page=None):
    page_data = models.Moviecol.query.order_by(models.Moviecol.addtime.desc()).paginate(page=page, per_page=10)
    return render_template('admin/moviecol_list.html', page_data=page_data)


# 删除电影收藏列表
@admin.route("/moviecol/del/<int:id>/", methods=["GET"])
@admin_login_decorator
def moviecol_del(id=None):
    moviecol = models.Moviecol.query.filter_by(id=id).first()
    db.session.delete(moviecol)
    db.session.commit()
    db.session.remove()
    return redirect(url_for('admin.moviecol_list', page=1))

app/admin/views/user.py
from .. import admin
from flask import render_template
from app import models
from .decorator import admin_login_decorator

# 会员列表
@admin.route("/user/list/<int:page>/", methods=["GET"])
@admin_login_decorator
def user_list(page=None):
    if not page:
        page = 1
    page_data = models.User.query.order_by(models.User.add_time.desc()).paginate(page=page, per_page=10)
    return render_template('admin/user_list.html', page_data=page_data)


# 查看会员登录日志列表
@admin.route("/user/loginlog/list/<int:page>/", methods=["GET"])
@admin_login_decorator
def user_loginlog_list(page=None):
    if not page:
        page = 1
    page_data = models.UserLog.query.join(
        models.User
    ).filter(
        models.UserLog.user_id == models.User.id
    ).order_by(
        models.UserLog.add_time.desc()
    ).paginate(page=page, per_page=10)
    # print(page_data.items)#[<UserLog 60>, <UserLog 59>, <UserLog 58>, <UserLog 57>, <UserLog 56>, <UserLog 55>, <UserLog 54>, <UserLog 53>, <UserLog 52>, <UserLog 51>]
    return render_template('admin/user_loginlog_list.html', page_data=page_data)


# 查看会员信息
@admin.route("/users/view/<int:id>", methods=["GET"])
@admin_login_decorator
def user_view(id):
    return ''

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.views.user
import app.home.views.movie
import app.home.views.index

app/home/views/decorator.py
from functools import wraps
from flask import session, redirect, url_for, request


# 装饰器
def user_login_decorator(func):
    @wraps(func)
    def inner(*args, **kwargs):
        if not session.get('user'):
            return redirect(url_for('home.login', next=request.url))
        return func(*args, **kwargs)

    return inner

app/home/views/index.py
from app.home import home
from flask import render_template, redirect, url_for
from ...models import Preview, Movie


@home.route('/')
def index(page=None):
    """
    preview_data = Preview.query.all()
    # print(preview_data)  # [<Preview 17>]
    first_preview_id = Preview.query.order_by(Preview.id.asc()).first().id  # <Preview 17>
    # first_preview_id = Preview.query.order_by(Preview.id.asc())  # sql
    # print(first_preview_id.id)
    return render_template('home/index.html', preview_data=preview_data, first_preview_id=first_preview_id)
    """
    return redirect(url_for('home.movie_list', page=1))


@home.route('/movie/<int:page>/')
def movie_list(page=None):
    # 预告
    preview_data = Preview.query.all()
    # print(preview_data)  # [<Preview 17>]
    first_preview_id = Preview.query.order_by(Preview.id.asc()).first().id  # <Preview 17>
    # first_preview_id = Preview.query.order_by(Preview.id.asc())  # sql
    # print(first_preview_id.id)
    # 电影列表
    page_date = Movie.query.order_by(Movie.add_time.desc()).paginate(page=page,per_page=12)
    # print(page_date)
    return render_template('home/index.html', preview_data=preview_data, first_preview_id=first_preview_id,
                           page_date=page_date)


@home.route('/index.html')
def index2():
    return render_template('home/index.html')


@home.route('/aboutwebsite.html')
def about_website():
    return render_template('home/aboutwebsite.html')


@home.route('/disclaimer.html')
def disclaimer():
    return render_template('home/disclaimer.html')


@home.route('/contact.html')
def contact():
    return render_template('home/contact.html')


@home.route('/blueprint.html')
def blueprint():
    return render_template('home/blueprint.html')

app/home/views/movie.py
from app.home import home
from flask import render_template, request, jsonify
from ... import models
from ...models import Comment, User, Movie
from app import db
from .user import user_login_decorator


# 搜索电影
@home.route("/movie/search/<int:page>/")
def movie_search(page=None):
    if page is None:
        page = 1
    key = request.args.get("key", "")
    movie_count = models.Movie.query.filter(
        models.Movie.title.ilike('%' + key + '%')
    ).count()
    page_data = models.Movie.query.filter(
        models.Movie.title.ilike('%' + key + '%')
    ).order_by(
        models.Movie.add_time.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/movie_search.html", page=page, key=key, page_data=page_data, movie_count=movie_count)


# 电影播放
@home.route("/movie/play/<int:id>.html", methods=["GET", "POST"])
def movie_play(id=None):
    movie = models.Movie.query.filter_by(id=id).first_or_404()

    movie.play_num += 1
    db.session.add(movie)
    db.session.commit()
    db.session.remove()
    movie = models.Movie.query.filter_by(id=id).first_or_404()
    comment_count = models.Comment.query.join(
        models.Movie
    ).filter(
        models.Comment.movie_id == models.Movie.id,
        models.Movie.id == id
    ).count()
    # print(comment_count)
    return render_template('home/movie_play.html', movie=movie, comment_count=comment_count)


# 接口：电影列表
# @home.route('/api/movie/list/', methods=['GET'])
# def get_movie_list():
#     ret = {'code': 1, 'msg': None}
#     try:
#         # movie_list = models.Movie.query#sql
#         movie_list = models.Movie.query.all()
#         # print(movie_list)  # [<Movie 2>, <Movie 3>]
#         ret['movies'] = []
#         for movie_obj in movie_list:
#             ret['movies'].append(
#                 {'id': movie_obj.id, 'info': movie_obj.info, 'logo': movie_obj.logo, 'title': movie_obj.title})
#         # print(ret)  # {'code': 1, 'msg': None, 'movies': [{'id': 2, 'info': '本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”，讲述了两个女主人公莉拉和埃莱娜的一生。本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”', 'logo': '20200716202150e030901ca71f45a7aa1fbf547e154e0b.jpeg'}, {'id': 3, 'info': '本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”，讲述了两个女主人公莉拉和埃莱娜的一生。本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”', 'logo': '20200716203111400d0e5b8ff544d4b277f692e9bea4b1.jpeg'}]}
#         # jsonify(ret)
#         # print(ret)  # {'code': 1, 'msg': None, 'movies': [{'id': 2, 'info': '本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”，讲述了两个女主人公莉拉和埃莱娜的一生。本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”', 'logo': '20200716202150e030901ca71f45a7aa1fbf547e154e0b.jpeg'}, {'id': 3, 'info': '本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”，讲述了两个女主人公莉拉和埃莱娜的一生。本剧改编自小说家埃莱娜·费兰特的“那不勒斯四部曲”', 'logo': '20200716203111400d0e5b8ff544d4b277f692e9bea4b1.jpeg'}]}
#     except Exception as e:
#         ret['code'] = 0
#         ret['msg'] = '获取电影列表失败！'
#         print(e)
#     return jsonify(ret)

# 添加电影收藏
@home.route("/moviecol/add/", methods=["GET", 'POST'])
def moviecol_add():
    user_id = request.args.get("user_id", "")
    movie_id = request.args.get("movie_id", "")
    moviecol = models.Moviecol.query.filter_by(
        user_id=user_id,
        movie_id=movie_id
    ).count()
    data = dict()
    if moviecol == 1:
        data = dict(ok=0)

    if moviecol == 0:
        moviecol = models.Moviecol(
            user_id=user_id,
            movie_id=movie_id
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)
    return jsonify(data)


@home.route("/moviecol/del/", methods=["GET", 'POST'])
def moviecol_cancel():
    user_id = request.args.get("user_id", "")
    movie_id = request.args.get("movie_id", "")
    moviecol = models.Moviecol.query.filter_by(user_id=user_id, movie_id=movie_id).first_or_404()
    # print(moviecol)
    data = dict(ok=0)  # {'ok': 0}表示取消失败
    if moviecol:
        db.session.delete(moviecol)
        db.session.commit()
        db.session.remove()
        data = dict(ok=1)  # {'ok': 1}表示取消成功
    return jsonify(data)


# 电影收藏状态(接口)
@home.route('/api/moviecol/status/')
def get_moviecol_status():
    user_id = request.args.get("user_id", "")
    movie_id = request.args.get("movie_id", "")
    moviecol = models.Moviecol.query.filter_by(
        user_id=user_id,
        movie_id=movie_id
    ).count()
    if moviecol == 1:
        data = dict(ok=1)  # {'ok': 1}表示已经收藏
    else:
        data = dict(ok=0)
    return jsonify(data)


# 添加评论(接口)
@home.route('/movie/comment/add/', methods=['POST'])
@user_login_decorator
def comment_add():
    ret = {'status': True, 'msg': None}
    try:
        # all = request.form  # ImmutableMultiDict([('comment_content', '你好'), ('user_id', '1'), ('movie_id', '3')])
        comment_content = request.form['comment_content']
        if len(comment_content) == 0:
            ret['status'] = False
            ret['msg'] = '评论内容不能为空！'
            return jsonify(ret)
        # print(comment_content, type(comment_content))  # 你好 <class 'str'>
        user_id = request.form['user_id']  # <class 'str'> 数据库是int，这里不使用int也可以
        movie_id = request.form['movie_id']  # <class 'str'>
        comment = Comment(
            content=comment_content,
            user_id=user_id,
            movie_id=movie_id
        )
        db.session.add(comment)
        db.session.commit()
        db.session.remove()
    except Exception as e:
        ret['status'] = False
        ret['msg'] = str(e)
        # ret['msg'] = '删除失败'
    return jsonify(ret)


# 评论列表(接口)
@home.route('/movie/comment/list/', methods=['GET'])
def show_movie_comment(page=None):
    if not None:
        page = 1
    ret = {'status': True, 'msg': None}
    try:
        movie_id = request.args.get('movie_id')  # <class 'str'>
        movie_comment_obj_list_page_data = Comment.query.join(
            User
        ).join(
            Movie
        ).filter(
            Movie.id == Comment.movie_id,
            User.id == Comment.user_id,
            Movie.id == movie_id
        ).order_by(
            Comment.add_time.desc()
        ).paginate(page=page, per_page=8)
        # 加不加all()都可以
        ret['user'] = []
        for obj in movie_comment_obj_list_page_data.items:
            # print(obj.user.face)  # 202007162204485797a85fb89d4360a3e1fd63660105c8.jpg
            # print(obj.content)  # 太好看了！
            ret['user'].append({'username': obj.user.name, 'face': obj.user.face, 'movie_comment': obj.content,
                                'add_time': str(obj.add_time)})
            # ret['user']['face'].append(obj.user.face)
            # ret['user']['movie_comment'].append(obj.content)

    except Exception as e:
        print(e)  # Entity '<class 'app.models.User'>' has no property 'movie_id'
        ret['status'] = False
        ret['msg'] = str(e)  # Entity '<class 'app.models.User'>' has no property 'movie_id'
        ret['msg'] = '获取评论列表失败！'
    """
    import json
    print(json.dumps(ret))  # {"status": true, "msg": null, "user": {"face": "202007162204485797a85fb89d4360a3e1fd63660105c8.jpg", "comment_content": "\u592a\u597d\u770b\u4e86\uff01"}}
    print(jsonify(ret))  # <Response 151 bytes [200 OK]>
    """
    jsonify(ret)
    print(
        ret)  # {'status': True, 'msg': None, 'user': {'face': '202007162204485797a85fb89d4360a3e1fd63660105c8.jpg', 'comment_content': '太好看了！'}}
    return jsonify(ret)

app/templates/home/aboutwebsite.html
{% extends 'home/home.html' %}
{% block css %}
{% endblock %}
{% block content %}
    <div class="container" style="padding: 0">
        <div class="row">
            <div class="col-md-12" style="padding:5px;">
                <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                    <li><a href="{{ url_for('home.index2') }}">首页</a></li>
                    <li class="active">关于本站</li>
                </ol>
                <div class="col-md-3" style="padding: 0">
                    <div class="panel panel-default" style="padding-bottom: 0">
                        <!--                <div class="panel-heading">关于本站</div>-->
                        <div class="panel-body">
                            <ul class="list-group" style="margin-bottom: 0">
                                <a href="{{ url_for('home.about_website') }}" class="list-group-item btn"
                                   style="font-weight: bold;background: brown;color: white">
                                    &nbsp;&nbsp;关于本站
                                </a>
                                <a href="{{ url_for('home.disclaimer') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;免责申明
                                </a>
                                <a href="{{ url_for('home.blueprint') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;本站蓝图
                                </a>
                                <a href="{{ url_for('home.contact') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;联系我们
                                </a>
                                <a href="" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;给我留言
                                </a>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-9" style="padding-right: 0">
                    <!--            <div class="panel panel-primary">-->
                    <!--                <div class="panel-heading">-->
                    <!--                    / 关于本站 / 关于运营-联系方式-->
                    <!--                </div>-->
                    <!--            </div>-->
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h5>1、本站面向全国互联网科技爱好者，是互联网信息资讯共享的友好平台，共享优质的互联网信息资讯、技术文章、源代码项目等……</h5>
                            <h5>2、项目源码由已申请开发者权限的用户上传，有的需要收取少量费用</h5>
                            <h5>3、开发者上传的项目源码，需要通过本平台的审核才能被用户下载</h5>
                            <h5>4、开发者上传的项目源码未通过审核，平台将予以驳回，不存储开发者未通过审核的资源</h5>
                        </div>
                        {% for v in range(18) %}<br>{% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/contact.html
{% extends 'home/home.html' %}
{% block css %}
{% endblock %}
{% block content %}
    <div class="container" style="padding: 0">
        <div class="row">
            <div class="col-md-12" style="padding:5px;">
                <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                    <li><a href="{{ url_for('home.index') }}">首页</a></li>
                    <li class="active">联系我们</li>
                </ol>
                <div class="col-md-3" style="padding: 0">
                    <div class="panel panel-default" style="padding-bottom: 0">
                        <!--                <div class="panel-heading">关于本站</div>-->
                        <div class="panel-body">
                            <ul class="list-group" style="margin-bottom: 0">
                                <a href="{{ url_for('home.about_website') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;关于本站
                                </a>
                                <a href="{{ url_for('home.disclaimer') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;免责申明
                                </a>
                                <a href="{{ url_for('home.blueprint') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;本站蓝图
                                </a>
                                <a href="{{ url_for('home.contact') }}" class="list-group-item btn"
                                   style="font-weight: bold;background: brown;color: white">
                                    &nbsp;&nbsp;联系我们
                                </a>
                                <a href="" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;给我留言
                                </a>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-9" style="padding-right: 0">
                    <!--            <div class="panel panel-primary">-->
                    <!--                <div class="panel-heading">-->
                    <!--                    / 关于本站 / 关于运营-联系方式-->
                    <!--                </div>-->
                    <!--            </div>-->
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h5>
                                <spqn class="glyphicon glyphicon-user"></spqn>
                                WeChat：18512152005
                            </h5>
                            <h5>
                                <spqn class="glyphicon glyphicon-user"></spqn>
                                QQ：3330447288
                            </h5>
                            <h5>
                                <span class="glyphicon glyphicon-envelope"></span>
                                E-mail&nbsp;：thanlon@sina.com
                            </h5>
                            <h5>
                                <spqn class="glyphicon glyphicon-link"></spqn>
                                博客地址：<a href="https://blog.csdn.net/Thanlon"
                                        target="_blank">https://blog.csdn.net/Thanlon</a>
                            </h5>
                        </div>
                        {% for v in range(18) %}<br>{% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/disclaimer.html
{% extends 'home/home.html' %}
{% block css %}
{% endblock %}
{% block content %}
    <div class="container" style="padding: 0">
        <div class="row">
            <div class="col-md-12" style="padding:5px;">
                <ol class="breadcrumb" style="margin-bottom: 0;padding: 10px">
                    <li><a href="{{ url_for('home.index') }}">首页</a></li>
                    <li class="active">免责申明</li>
                </ol>
                <div class="col-md-3" style="padding: 0">
                    <div class="panel panel-default" style="padding-bottom: 0">
                        <!--                <div class="panel-heading">关于本站</div>-->
                        <div class="panel-body">
                            <ul class="list-group" style="margin-bottom: 0">
                                <a href="{{ url_for('home.about_website') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;关于本站
                                </a>
                                <a href="{{ url_for('home.disclaimer') }}" class="list-group-item btn"
                                   style="font-weight: bold;background:brown;;color: white">
                                    &nbsp;&nbsp;免责申明
                                </a>
                                <a href="{{ url_for('home.blueprint') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;本站蓝图
                                </a>
                                <a href="{{ url_for('home.contact') }}" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;联系我们
                                </a>
                                <a href="" class="list-group-item btn"
                                   style="font-weight: bold;">
                                    &nbsp;&nbsp;给我留言
                                </a>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-9" style="padding-right: 0">
                    <!--            <div class="panel panel-primary">-->
                    <!--                <div class="panel-heading">-->
                    <!--                    / 关于本站 / 关于运营-联系方式-->
                    <!--                </div>-->
                    <!--            </div>-->
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h5>1、用户用于注册的个人相关信息，本站均通过加密算法进行加密，切实保护用户的隐私、保障用户的合法权益</h5>
                            <h5>2、请用户规范自己的行为，发表文章或评论中切不可出现反政治、有暴力倾向、恐吓、色情等的危害公共安全的言论</对于违反></h5>
                            <h5>3、特此申明：注册成为本站用户即表示您已同意本协议</h5>
                        </div>
                        {% for v in range(18) %}<br>{% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{% endblock %}

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员信息
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comment_list',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.login_log',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol_list',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;我的收藏
        </a>
    </div>
</div>

app/templates/home/movie_search.html
{% extends "home/home.html" %}
{% import "home/pagination/search_page.html" as pg %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;margin-bottom: 0">
                <li>找到了{{ movie_count }}个与"{{ key }}"有关的视频！</li>
            </ol>
        </div>
        <div class="col-md-12" style="margin-top: 15px">
            {% for v in page_data.items %}
                <div class="media">
                    <div class="media-left" style="padding: 2px">
                        <a href="">
                            <img class="img-rounded" height="110px" width="85px"
                                 src="{{ url_for('static',filename='admin/uploads/movielogos/'+v.logo) }}"
                                 alt="{{ v.title }}">
                        </a>
                    </div>
                    <div class="media-body" style="padding: 2px">
                        <div class="media-heading" style="font-size: 15px;margin: 5px;">{{ v.title }}
                            <a href="{{ url_for('home.movie_play',id=v.id) }}" class="label label-danger pull-right">
                                <span class="glyphicon glyphicon-play"></span>播放影片
                            </a>
                        </div>
                        <div style="margin: 5px">{{ v.info }}</div>
                    </div>
                </div>
            {% endfor %}
            <hr>
            <div class="col-md-12 text-center">
                {{ pg.page(page_data,'home.movie_search') }}
            </div>
            <!--
              <div class="col-md-3" style="padding:5px 3px">
                  <div class="panel panel-default">
                      <div class="panel-heading" id="news"><span class="glyphicon glyphicon-fire"></span>热门搜索</div>
                      <div>
                          <li style="padding: 11px 15px" href="#" class="list-group-item"><span
                                  class="badge" style="background-color: #3379b7;">1200</span><a
                                  href=""
                                  style="color: #333333">我的天才女友第二季</a>
                          </li>
                          <li style="padding: 11px 15px" href="#" class="list-group-item"><span
                                  class="badge" style="background-color: #3379b7;">1100</span><a
                                  href=""
                                  style="color: #333333">我的天才女友第一季</a>
                          </li>
                          <li style="padding: 11px 15px" href="#" class="list-group-item"><span class="badge"
                                                                                                style="background-color: #3379b7;">890</span><a
                                  href=""
                                  style="color: #333333">我的天才女友第二季</a>
                          </li>
                          <li style="padding: 11px 15px" href="#" class="list-group-item"><span class="badge"
                                                                                                style="background-color: #3379b7;">798</span><a
                                  href=""
                                  style="color: #333333">我的天才女友第二季</a>
                          </li>
                          <li style="padding: 11px 15px" href="#" class="list-group-item"><span class="badge"
                                                                                                style="background-color: #3379b7;">509</span><a
                                  href=""
                                  style="color: #333333">我的天才女友第二季</a>
                          </li>
                      </div>
                  </div>
              </div>
              -->
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $('#nav-movie').css({'color': '#a52a2a'})
    </script>
{% endblock %}

app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% import "home/pagination/home_page.html" as pg %}
{% block css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='home/css/user.css') }}/">
    <style>
        .list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
            background-color: brown;
            border: none;
        }

        .panel-default > .panel-heading {
            color: #333;
            background-color: #ccc;
            border-color: #f5f5f5;
        }
    </style>
{% endblock %}
{% block content %}
    {% include "home/menu.html" %}
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    {% for v in page_data.items %}
                        <div class="media">
                            <div class="media-left">
                                <a href="{{ url_for('home.movie_play',id=v.movie.id) }}">
                                    <img class="media-object" style="width:120px;height:60px;" src="/static/admin/uploads/movielogos/{{ v.movie.logo }}" alt="">
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">
{#                                    {{ v.movie.title }}#}
                                    <a href="{{ url_for('home.movie_play',id=v.movie.id) }}" class="label label-danger pull-right" target="_blank">
                                        <span class="glyphicon glyphicon-play"></span>播放影片
                                    </a>
                                </h4>
                                 <h5 style="margin: 5px;line-height: 1.5">{{ v.movie.info }}</h5>
                            </div>
                        </div>
                    {% endfor %}
                 <hr>
                </div>
                <div class="col-md-12 text-center" style="margin-top:6px;">
                    {{ pg.page(page_data,'home.moviecol_list') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("#m-5").addClass("active");
        });
    </script>
{% endblock %}